cluster_name                 = "plombardi"
hosted_zone                  = "kubernaut.io"
instance_type                = "m4.large"
image_id                     = "ami-5d4e4526"
ssh_public_key               = "/home/plombardi/.ssh/datawire_rsa.pub"
bootstrap_script             = "kubernaut-io-v1-nostart.bash"
