cluster_name                 = "plombardi"
hosted_zone                  = "kubernaut.io"
instance_type                = "m4.large"
image_id                     = "ami-a2233eb4"
ssh_public_key               = "/home/plombardi/.ssh/plombardi_rsa.pub"
kubernetes_networking_plugin = "calico"
