#!/usr/bin/env bash

PRIVATE_KEY=${1:?"PRIVATE_KEY must be set!"}

cd standalone
scp -o StrictHostKeyChecking=no -i ${PRIVATE_KEY} centos@$(terraform output kubernaut_fqdn | tr -d '\n'):/home/centos/kubeconfig .
cd -