#!/usr/bin/env bash
NAME=${1:?"Name must be set!"}
SSH_KEY=${2:-"~/.ssh/id_rsa"}

cd standalone
cat >terraform.tfvars <<EOF
cluster_name                 = "${NAME}"
hosted_zone                  = "kubernaut.io"
instance_type                = "m4.large"
image_id                     = "ami-5d4e4526"
ssh_public_key               = "${SSH_KEY}"
bootstrap_script             = "kubernaut-io-v1-nostart.bash"
EOF

terraform plan -out plan.out
terraform apply plan.out
